repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: v21.12b0  # Use a versão mais recente disponível
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.3   # Use a versão mais recente disponível
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.1.1    # Use a versão mais recente disponível
    hooks:
      - id: flake8
